DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS PUBLIC.FILMS (
	FILM_ID INTEGER NOT NULL AUTO_INCREMENT,
	FILM_NAME CHARACTER VARYING NOT NULL,
	DESCRIPTION CHARACTER VARYING,
	RELEASE_DATE DATE,
	DURATION INTEGER,
	MPA_ID INTEGER
);


CREATE TABLE IF NOT EXISTS PUBLIC.MPA (
	MPA_ID INTEGER NOT NULL AUTO_INCREMENT,
	MPA_TYPE CHARACTER VARYING NOT NULL
);


CREATE TABLE IF NOT EXISTS PUBLIC.GENRE_FILM (
	GENRE_ID INTEGER,
	FILM_ID INTEGER
);


CREATE TABLE IF NOT EXISTS PUBLIC.GENRE (
	GENRE_ID INTEGER NOT NULL AUTO_INCREMENT,
	GENRE_TYPE CHARACTER VARYING NOT NULL
);


CREATE TABLE IF NOT EXISTS PUBLIC.LIKES (
	FILM_ID INTEGER,
	USER_ID INTEGER
);

CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
	USER_ID INTEGER NOT NULL AUTO_INCREMENT,
	EMAIL CHARACTER VARYING,
	LOGIN CHARACTER VARYING,
	USER_NAME CHARACTER VARYING,
	BIRTHDAY DATE
);

CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDS (
	USER_ID INTEGER,
	FRIEND_ID INTEGER,
	STATUS BOOLEAN
);


ALTER TABLE PUBLIC.FILMS ADD CONSTRAINT IF NOT EXISTS FILMS_PK PRIMARY KEY (FILM_ID);

ALTER TABLE PUBLIC.MPA ADD CONSTRAINT IF NOT EXISTS MPA_PK PRIMARY KEY (MPA_ID);

ALTER TABLE PUBLIC.GENRE ADD CONSTRAINT IF NOT EXISTS GENRE_PK PRIMARY KEY (GENRE_ID);

ALTER TABLE PUBLIC.USERS ADD CONSTRAINT IF NOT EXISTS USERS_PK PRIMARY KEY (USER_ID);


ALTER TABLE PUBLIC.FILMS ADD CONSTRAINT IF NOT EXISTS FILMS_FK FOREIGN KEY (MPA_ID) REFERENCES PUBLIC.MPA(MPA_ID);

ALTER TABLE PUBLIC.GENRE_FILM ADD CONSTRAINT IF NOT EXISTS GENRE_FILM_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID);

ALTER TABLE PUBLIC.GENRE_FILM ADD CONSTRAINT IF NOT EXISTS GENRE_FILM_FK_1 FOREIGN KEY (GENRE_ID) REFERENCES PUBLIC.GENRE(GENRE_ID);

ALTER TABLE PUBLIC.LIKES ADD CONSTRAINT IF NOT EXISTS LIKES_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID);

ALTER TABLE PUBLIC.LIKES ADD CONSTRAINT IF NOT EXISTS LIKES_FK_1 FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID);

ALTER TABLE PUBLIC.FRIENDS ADD CONSTRAINT IF NOT EXISTS FRIENDS_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID);

ALTER TABLE PUBLIC.FRIENDS ADD CONSTRAINT IF NOT EXISTS FRIENDS_FK_1 FOREIGN KEY (FRIEND_ID) REFERENCES PUBLIC.USERS(USER_ID);




